### ISSUE TITLE
Meizu 5 Pro m86/turbo Exynos 7420

### ISSUE THREAD

**Issue by elelel** [krzk/linux-vendor-backup#1]
Hi, I noticed this repository does not contain vendor source for Meizue 5 Pro which is 7420-based. The official vendor release for Android and Ubuntu can be found here: https://github.com/meizuosc/m576 If it qualifies, it can be added as a branch here.

**Comment by krzk** [comment]
Sure, I can add it:
https://github.com/krzk/linux-vendor-backup/tree/meizu/meizu-pro-5-m576-exynos7420-android-dump
https://github.com/krzk/linux-vendor-backup/tree/meizu/meizu-pro-5-m576-exynos7420-ubuntu-dump
